// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RazorPagesChess.Migrations
{
    [DbContext(typeof(RazorPagesChessContext))]
    [Migration("20220221040328_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("RazorPagesChess.Models.Chess", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("colour")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("inCheck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quardLetter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quardNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Chess");
                });
#pragma warning restore 612, 618
        }
    }
}
